import { AuthProvider } from "@/hooks/use-auth";
import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = auth();

    return (
        <html lang="en">
            <AuthProvider session={session}>
                <body className={inter.className}>{children}</body>
            </AuthProvider>
        </html>
    );
}
